//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.17929
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yabe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int GUI_SplitterLeft {
            get {
                return ((int)(this["GUI_SplitterLeft"]));
            }
            set {
                this["GUI_SplitterLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int GUI_SplitterRight {
            get {
                return ((int)(this["GUI_SplitterRight"]));
            }
            set {
                this["GUI_SplitterRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int GUI_SplitterButtom {
            get {
                return ((int)(this["GUI_SplitterButtom"]));
            }
            set {
                this["GUI_SplitterButtom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size GUI_FormSize {
            get {
                return ((global::System.Drawing.Size)(this["GUI_FormSize"]));
            }
            set {
                this["GUI_FormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string GUI_FormState {
            get {
                return ((string)(this["GUI_FormState"]));
            }
            set {
                this["GUI_FormState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Udp_ExclusiveUseOfSocket {
            get {
                return ((bool)(this["Udp_ExclusiveUseOfSocket"]));
            }
            set {
                this["Udp_ExclusiveUseOfSocket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MSTP_DisplayFreeAddresses {
            get {
                return ((bool)(this["MSTP_DisplayFreeAddresses"]));
            }
            set {
                this["MSTP_DisplayFreeAddresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MSTP_LogStateMachine {
            get {
                return ((bool)(this["MSTP_LogStateMachine"]));
            }
            set {
                this["MSTP_LogStateMachine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal DefaultRetries {
            get {
                return ((decimal)(this["DefaultRetries"]));
            }
            set {
                this["DefaultRetries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal DefaultTimeout {
            get {
                return ((decimal)(this["DefaultTimeout"]));
            }
            set {
                this["DefaultTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("47808")]
        public decimal DefaultUdpPort {
            get {
                return ((decimal)(this["DefaultUdpPort"]));
            }
            set {
                this["DefaultUdpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38400")]
        public decimal DefaultBaudrate {
            get {
                return ((decimal)(this["DefaultBaudrate"]));
            }
            set {
                this["DefaultBaudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public decimal DefaultSourceAddress {
            get {
                return ((decimal)(this["DefaultSourceAddress"]));
            }
            set {
                this["DefaultSourceAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127")]
        public decimal DefaultMaxMaster {
            get {
                return ((decimal)(this["DefaultMaxMaster"]));
            }
            set {
                this["DefaultMaxMaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal DefaultMaxInfoFrames {
            get {
                return ((decimal)(this["DefaultMaxInfoFrames"]));
            }
            set {
                this["DefaultMaxInfoFrames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Subscriptions_IssueConfirmedNotifies {
            get {
                return ((bool)(this["Subscriptions_IssueConfirmedNotifies"]));
            }
            set {
                this["Subscriptions_IssueConfirmedNotifies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public uint Subscriptions_Lifetime {
            get {
                return ((uint)(this["Subscriptions_Lifetime"]));
            }
            set {
                this["Subscriptions_Lifetime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GUI_LastFilename {
            get {
                return ((string)(this["GUI_LastFilename"]));
            }
            set {
                this["GUI_LastFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultDownloadSpeed {
            get {
                return ((int)(this["DefaultDownloadSpeed"]));
            }
            set {
                this["DefaultDownloadSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte Segments_ProposedWindowSize {
            get {
                return ((byte)(this["Segments_ProposedWindowSize"]));
            }
            set {
                this["Segments_ProposedWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public byte Segments_Max {
            get {
                return ((byte)(this["Segments_Max"]));
            }
            set {
                this["Segments_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimeSynchronize_UTC {
            get {
                return ((bool)(this["TimeSynchronize_UTC"]));
            }
            set {
                this["TimeSynchronize_UTC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Udp_DontFragment {
            get {
                return ((bool)(this["Udp_DontFragment"]));
            }
            set {
                this["Udp_DontFragment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1472")]
        public int Udp_MaxPayload {
            get {
                return ((int)(this["Udp_MaxPayload"]));
            }
            set {
                this["Udp_MaxPayload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultPreferStructuredView {
            get {
                return ((bool)(this["DefaultPreferStructuredView"]));
            }
            set {
                this["DefaultPreferStructuredView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultUdpIp {
            get {
                return ((string)(this["DefaultUdpIp"]));
            }
            set {
                this["DefaultUdpIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LOWEST_AND_DEFAULT")]
        public global::System.IO.BACnet.BacnetWritePriority DefaultWritePriority {
            get {
                return ((global::System.IO.BACnet.BacnetWritePriority)(this["DefaultWritePriority"]));
            }
            set {
                this["DefaultWritePriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int YabeDeviceId {
            get {
                return ((int)(this["YabeDeviceId"]));
            }
            set {
                this["YabeDeviceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultBBMD {
            get {
                return ((string)(this["DefaultBBMD"]));
            }
            set {
                this["DefaultBBMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint Subscriptions_ReplacementPollingPeriod {
            get {
                return ((uint)(this["Subscriptions_ReplacementPollingPeriod"]));
            }
            set {
                this["Subscriptions_ReplacementPollingPeriod"] = value;
            }
        }
    }
}
