namespace System.IO.BACnet;

public enum BacnetBvlcV6Functions : byte
{
    BVLC_RESULT = 0,
    BVLC_ORIGINAL_UNICAST_NPDU = 1,
    BVLC_ORIGINAL_BROADCAST_NPDU = 2,
    BVLC_ADDRESS_RESOLUTION = 3,
    BVLC_FORWARDED_ADDRESS_RESOLUTION = 4,
    BVLC_ADDRESS_RESOLUTION_ACK = 5,
    BVLC_VIRTUAL_ADDRESS_RESOLUTION = 6,
    BVLC_VIRTUAL_ADDRESS_RESOLUTION_ACK = 7,
    BVLC_FORWARDED_NPDU = 8,
    BVLC_REGISTER_FOREIGN_DEVICE = 9,
    BVLC_DELETE_FOREIGN_DEVICE_TABLE_ENTRY = 0xA,
    BVLC_SECURE_BVLC = 0xB,
    BVLC_DISTRIBUTE_BROADCAST_TO_NETWORK = 0xC
}
